package dreamsuite.insert;

import dreamsuite.koneksi;
import static dreamsuite.koneksi.getKoneksi;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class InsertPemesanan extends javax.swing.JFrame {
    public Connection con;
    public Statement st;
    public ResultSet rs;
    /**
     * Creates new form Staf
     */
    public InsertPemesanan() {
        initComponents();
    }
     public void insert(){
        String NoReservasi = jTextFieldNoReservasi.getText();
        String TipeKamar = jTextFieldTipeKamar.getText();
        String JumlahKamar = jTextFieldJumlahKamar.getText();
        String TanggalCheckIn = jTextFieldCheckIn.getText();
        String TanggalCheckOut= jTextFieldCheckOut.getText(); 
        String JumlahPenginap = jTextFieldPenginap.getText();
        String IDAdmin = jTextFieldIdAdmin.getText();
        String NoKTPTamu = jTextFieldNoKTPTamu.getText();
        String NoLaporan = jTextFieldNoLaporan.getText();
        String request = jTextAreaRequest.getText();
        try{
            Connection kon = getKoneksi();
            Statement s = kon.createStatement();
            String query = "INSERT INTO pemesanan VALUES('"+NoReservasi+"', '"+TipeKamar+"', '"+JumlahKamar+"', '"+TanggalCheckIn+"', '"+TanggalCheckOut+"', '"+JumlahPenginap+"','"+IDAdmin+"','"+NoKTPTamu+"','"+NoLaporan+"')";
            int r = s.executeUpdate(query);
            String query2 = "INSERT INTO specialrequest VALUES('"+NoReservasi+"', '"+request+"')";
            int d = s.executeUpdate(query2);
        } catch (SQLException ex){
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1NoReservasi = new javax.swing.JLabel();
        jLabel2TipeKamar = new javax.swing.JLabel();
        jLabel3JumlahKamar = new javax.swing.JLabel();
        jLabel4CheckIn = new javax.swing.JLabel();
        jLabel5CheckOut = new javax.swing.JLabel();
        jLabel6Penginap = new javax.swing.JLabel();
        jLabel7IDAdmin = new javax.swing.JLabel();
        jLabel8NoKTPTamu = new javax.swing.JLabel();
        jButton1Simpan = new javax.swing.JButton();
        jTextFieldCheckOut = new javax.swing.JTextField();
        jTextFieldCheckIn = new javax.swing.JTextField();
        jTextFieldJumlahKamar = new javax.swing.JTextField();
        jTextFieldTipeKamar = new javax.swing.JTextField();
        jTextFieldNoReservasi = new javax.swing.JTextField();
        jTextFieldPenginap = new javax.swing.JTextField();
        jTextFieldIdAdmin = new javax.swing.JTextField();
        jTextFieldNoKTPTamu = new javax.swing.JTextField();
        jLabel8NoLaporan = new javax.swing.JLabel();
        jTextFieldNoLaporan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRequest = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pemesanan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1NoReservasi.setText("No Reservasi");

        jLabel2TipeKamar.setText("Tipe Kamar");

        jLabel3JumlahKamar.setText("Jumlah Kamar");

        jLabel4CheckIn.setText("Tanggal Check In");

        jLabel5CheckOut.setText("Tanggal Check Out");

        jLabel6Penginap.setText("Jumlah Penginap");

        jLabel7IDAdmin.setText("ID Admin");

        jLabel8NoKTPTamu.setText("NO KTP Tamu");

        jButton1Simpan.setText("Simpan");
        jButton1Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SimpanActionPerformed(evt);
            }
        });

        jTextFieldCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCheckOutActionPerformed(evt);
            }
        });

        jTextFieldCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCheckInActionPerformed(evt);
            }
        });

        jTextFieldJumlahKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJumlahKamarActionPerformed(evt);
            }
        });

        jTextFieldTipeKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipeKamarActionPerformed(evt);
            }
        });

        jTextFieldNoReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNoReservasiActionPerformed(evt);
            }
        });

        jTextFieldPenginap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPenginapActionPerformed(evt);
            }
        });

        jTextFieldIdAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdAdminActionPerformed(evt);
            }
        });

        jTextFieldNoKTPTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNoKTPTamuActionPerformed(evt);
            }
        });

        jLabel8NoLaporan.setText("No Laporan");

        jTextFieldNoLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNoLaporanActionPerformed(evt);
            }
        });

        jLabel1.setText("Special Request");

        jTextAreaRequest.setColumns(20);
        jTextAreaRequest.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRequest);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1Simpan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1NoReservasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNoReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2TipeKamar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3JumlahKamar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldJumlahKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4CheckIn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jTextFieldCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5CheckOut)
                                    .addComponent(jLabel6Penginap)
                                    .addComponent(jLabel7IDAdmin)
                                    .addComponent(jLabel8NoKTPTamu)
                                    .addComponent(jLabel8NoLaporan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldPenginap)
                                    .addComponent(jTextFieldCheckOut)
                                    .addComponent(jTextFieldIdAdmin)
                                    .addComponent(jTextFieldNoKTPTamu)
                                    .addComponent(jTextFieldNoLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1NoReservasi)
                    .addComponent(jTextFieldNoReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2TipeKamar)
                    .addComponent(jTextFieldTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3JumlahKamar)
                    .addComponent(jTextFieldJumlahKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4CheckIn)
                    .addComponent(jTextFieldCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5CheckOut)
                    .addComponent(jTextFieldCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6Penginap)
                    .addComponent(jTextFieldPenginap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7IDAdmin)
                    .addComponent(jTextFieldIdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8NoKTPTamu)
                    .addComponent(jTextFieldNoKTPTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8NoLaporan)
                    .addComponent(jTextFieldNoLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1Simpan)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SimpanActionPerformed
        insert();
    }//GEN-LAST:event_jButton1SimpanActionPerformed

    private void jTextFieldCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCheckOutActionPerformed

    private void jTextFieldCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCheckInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCheckInActionPerformed

    private void jTextFieldJumlahKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJumlahKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJumlahKamarActionPerformed

    private void jTextFieldTipeKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipeKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipeKamarActionPerformed

    private void jTextFieldNoReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoReservasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNoReservasiActionPerformed

    private void jTextFieldPenginapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPenginapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPenginapActionPerformed

    private void jTextFieldIdAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdAdminActionPerformed

    private void jTextFieldNoKTPTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoKTPTamuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNoKTPTamuActionPerformed

    private void jTextFieldNoLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNoLaporanActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1NoReservasi;
    private javax.swing.JLabel jLabel2TipeKamar;
    private javax.swing.JLabel jLabel3JumlahKamar;
    private javax.swing.JLabel jLabel4CheckIn;
    private javax.swing.JLabel jLabel5CheckOut;
    private javax.swing.JLabel jLabel6Penginap;
    private javax.swing.JLabel jLabel7IDAdmin;
    private javax.swing.JLabel jLabel8NoKTPTamu;
    private javax.swing.JLabel jLabel8NoLaporan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaRequest;
    private javax.swing.JTextField jTextFieldCheckIn;
    private javax.swing.JTextField jTextFieldCheckOut;
    private javax.swing.JTextField jTextFieldIdAdmin;
    private javax.swing.JTextField jTextFieldJumlahKamar;
    private javax.swing.JTextField jTextFieldNoKTPTamu;
    private javax.swing.JTextField jTextFieldNoLaporan;
    private javax.swing.JTextField jTextFieldNoReservasi;
    private javax.swing.JTextField jTextFieldPenginap;
    private javax.swing.JTextField jTextFieldTipeKamar;
    // End of variables declaration//GEN-END:variables
}
